# Generated by Django 3.1.4 on 2021-01-12 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0014_auto_20210111_1301'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='watch_list',
            field=models.ManyToManyField(blank=True, related_name='watchlist', to='auctions.Listing'),
        ),
    ]
