# Generated by Django 3.1.4 on 2021-01-12 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0015_user_watch_list'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='watch_list',
            new_name='watchlist',
        ),
    ]
