# Generated by Django 3.1.4 on 2021-01-13 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0026_auto_20210113_0850'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listing',
            name='user',
        ),
        migrations.RemoveField(
            model_name='user',
            name='watchlist',
        ),
    ]
