# Generated by Django 3.1.4 on 2021-01-13 21:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0031_auto_20210113_1314'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='price',
            new_name='amount',
        ),
    ]
