# Generated by Django 3.1.4 on 2021-01-14 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0033_bid_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='catagory',
            field=models.CharField(choices=[('non', 'No catagory'), ('fas', 'Fashion'), ('hom', 'Home'), ('ele', 'Electronics'), ('toy', 'Toys')], default=1, max_length=3),
            preserve_default=False,
        ),
    ]
