# Generated by Django 3.1.4 on 2021-01-14 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0034_listing_catagory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Catagory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=23)),
            ],
        ),
        migrations.RemoveField(
            model_name='listing',
            name='catagory',
        ),
        migrations.AddField(
            model_name='listing',
            name='catagory',
            field=models.ManyToManyField(blank=True, related_name='catagory', to='auctions.Catagory'),
        ),
    ]
