# Generated by Django 3.1.4 on 2021-01-15 17:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0037_comment_listing'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
